### ISSUE TITLE
Some links are not tracked in cli but tracked in the web app

### ISSUE THREAD

**Issue by khaosdoctor** [sinedied/cxa-track#2]
I noticed some links are not tracked in the CLI app but when I use the social linker online it tracks ok.

I think it might be due to the allowed URL list here: https://github.com/sinedied/cxa-track/blob/a9ac9efea3c574ed102d5166bfcbbd813ca79af0/lib/tracking.js#L9-L20

Which is different from the web version: https://github.com/spboyer/advocate-linkers/blob/master/scripts/cda-tracker/src/cda-tracker.js#L4-L9

Then some links are not tracked in one but tracked in the other. I just wanted to check if this list is correct, I can provide the PR if needeed :)

**Comment by sinedied** [comment]
I originally tooks the whitelist from our tracking guidelines document, so unless the policies changed the list used in the web version might be a bit too broad, as all microsoft.com subdomains are not tracked 😉 
It might be useful to check with Daisy or Eva on this one, and update either list accordingly, I will put a message on slack.

**Comment by khaosdoctor** [comment]
Cool, I'll manage to get the most up to date, If the list here is not up to date I'll open an issue on the web tool so we can sync those.

Otherwise, maybe both versions are differing from the link list, maybe we have to update both of them

**Comment by khaosdoctor** [comment]
Created the PR https://github.com/spboyer/advocate-linkers/pull/32
